name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: snickerbockers/submodules-init@v4
    - name: Validate site
      run: make validate
      env:
        HUGO_ENV: ${{ startsWith(github.ref, 'refs/heads/release-') && 'production' || 'staging' }}
    - uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'tar'
        filename: 'public.tar.gz'
        path: ./public
    - name: Extract branch
      id: extract_branch
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: harikube/harikube.github.io.git
        ref: main
        path: harikube.github.io.git
        token: ${{ secrets.GIT_TOKEN }}
        github-server-url: https://github.com
        persist-credentials: true
    - name: Release to github.io
      run: |
        rsync -az --delete --exclude CNAME --exclude .git --exclude .gitignore ./public/ ./harikube.github.io.git/
        cd harikube.github.io.git ; \
          git config user.email "devnull@harikube.info" && \
          git config user.name "harikube.info bot" && \
          git add -A && \
          git commit -m"Updating site to ${{ steps.extract_branch.outputs.branch }}" && \
          git push
    - name: Create release
      if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
      uses: mhmxs/milestone-release-action@main
      with:
        milestone-title: ${{ steps.extract_branch.outputs.branch }}
        pre-body: |
            # HariKube Website
            
            ## Release Notes
        draft: false
        prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
        files: README.md,LICENSE,public.tar.gz
