name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: snickerbockers/submodules-init@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Generate site
      run: make gen
      env:
        HUGO_ENV: ${{ startsWith(github.ref, 'refs/heads/release-') && 'production' || 'staging' }}
    - uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'tar'
        filename: 'public.tar.gz'
        path: ./public
    - name: Extract branch
      id: extract_branch
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/harikube.info:${{ steps.extract_branch.outputs.branch }}
    - name: Create release
      if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.extract_branch.outputs.branch }}
        name: ${{ steps.extract_branch.outputs.branch }}
        body: |
            # HariKube Website
            
            `docker pull ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/harikube.info:${{ steps.extract_branch.outputs.branch }}`
        draft: true
        prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
        generate_release_notes: true
        files: |
          README.md
          LICENSE
          public.tar.gz
